nelmio_api_doc:
    type_info: true
    documentation:
        paths:
            /api/login:
                post:
                    operationId: postCredentialsItem
                    tags:
                        - Token JWT
                    summary: Permet d'obtenir le token JWT pour se logger.
                    requestBody:
                        description: Crée un nouveau token JWT
                        content:
                            application/json:
                                schema:
                                    $ref: '#/components/schemas/Credentials'
                    responses:
                        '200':
                            description: Récupère le token JWT
                            content:
                                application/json:
                                    schema:
                                        $ref: '#/components/schemas/Token'

        info:
            title: Greengoodies API
#            description:
            version: 1.0.0
        components:

            schemas:
                Token:
                    type: object
                    properties:
                        token:
                            type: string
                            readOnly: true
                Credentials:
                    type: object
                    properties:
                        username:
                            type: string
                            default: adrienforce@icloud.com
                        password:
                            type: string
                            default: password

            securitySchemes:
                Bearer:
                    type: http
                    scheme: bearer
                    bearerFormat: JWT


    areas: # to filter documented areas
        path_patterns:
            - ^/api(?!/doc$) # Accepts routes under /api except /api/doc
